Add endpoint to create gist
phadej/github pull request #455
Opened 2020-12-31 19:04 UTC by matsubara0507

ref https://docs.github.com/rest/reference/gists#create-a-gist

```hs
ghci> github (OAuth "...") $ createGistR (NewGist "" (HashMap.fromList [("hoge.txt", NewGistFile "abc")]) False)
Right (Gist {...})
```

about `NewGist`'s fields: 

- `description` is optional param according to reference. But, when use `Maybe` type and `Nothing`, occur error `Invalid request.\\n\\nFor 'properties/description', nil is not a string.`. So, `description` param is `Text` type.
- `public` is optional param according to reference. But, when use `Maybe` type and `Nothing`,  occur error `Left (ParseError "Error in $.public: expected Bool, but encountered Null")`. So, `public` param is `Bool` type.

2020-12-31 19:11 UTC, phadej commented
```json
{ "foo": null }
```

is not the same as 

```json
{}
```.

See https://github.com/phadej/github/blob/master/src/GitHub/Data/Milestone.hs#L56-L65 for an example (filtering out `null`s).

2020-12-31 19:13 UTC, phadej requested changes

2020-12-31 19:13 UTC, phadej commented on src/GitHub/Data/Gists.hs
> +    toJSON (NewGist { newGistDescription = description
brackets are redundant

2021-01-01 06:11 UTC, matsubara0507 commented on src/GitHub/Data/Gists.hs
> +    toJSON (NewGist { newGistDescription = description
thx, remove `()` 91424a9

2021-01-01 06:15 UTC, matsubara0507 commented
Thank you. Use `Maybe a` type to `description` and `public` params with `filter notNull`. c44824b

2021-10-09 21:10 UTC, merged